---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubernetes-mcp-server-chart.fullname" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "kubernetes-mcp-server-chart.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "kubernetes-mcp-server-chart.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        {{- include "kubernetes-mcp-server-chart.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ .Values.mcpServer.serviceAccountName }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.mcpServer.port }}
              protocol: TCP
          command: ["./kubernetes-mcp-server"]
          args:
            - "--sse-port"
            - "{{ .Values.mcpServer.port }}"
            {{- if .Values.mcpServer.disableDestructive }}
            - "--disable-destructive"
            {{- end }}
            {{- if .Values.mcpServer.logLevel }}
            - "--log-level"
            - "{{ .Values.mcpServer.logLevel }}"
            {{- end }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
          # livenessProbe:
          #   httpGet:
          #     path: /mcp
          #     port: http
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          #   timeoutSeconds: 5
          #   failureThreshold: 3
          # readinessProbe:
          #   httpGet:
          #     path: /mcp
          #     port: http
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          #   timeoutSeconds: 5
          #   failureThreshold: 3
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi