{{- if .Values.namespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    {{- include "kubernetes-mcp-server-chart.labels" . | nindent 4 }}
    name: {{ .Values.namespace }}
{{- end }}
