---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubernetes-mcp-server-chart.fullname" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "kubernetes-mcp-server-chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.mcpServer.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kubernetes-mcp-server-chart.selectorLabels" . | nindent 4 }}
