---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.name }}
spec:
  to:
    kind: Service
    name: {{ .Values.name }}-service
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None