---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: http
      port: 8321
      targetPort: 8321
      protocol: TCP
  selector:
    app: {{ .Values.name }}
