# Default values for gradio-chart.
# This is a simplified Helm chart for deploying Gradio applications.

# Namespace Configuration
global:
  namespace: "intelligent-cd"

llamaStack:
  url: "http://llama-stack-service.intelligent-cd.svc.cluster.local:8321"
  model: "llama-3-2-3b"

# Application Configuration
replicaCount: 1

image:
  repository: "quay.io/alopezme/intelligent-cd-gradio"
  tag: "latest"

nameOverride: ""
fullnameOverride: "gradio"

# Exposure Configuration
exposure:
  # Type of exposure: none, ingress, or route
  type: "route"
  # Hostname for ingress or route (optional)
  host: ""

# Resources
resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "1000m"
    memory: "2Gi"
